"""Download real daily prices (in INR) and volumes for big NSE stocks and save them in data/.

Run once:  py data_nse.py
Prices are adjusted for splits and dividends, so daily changes are real returns.
"""
import os
import pandas as pd
import yfinance as yf

START = "2015-01-01"
MIN_DAYS = 2190   # drop stocks with too little history

# large NSE companies (mostly the Nifty 50). Today's big companies only -> see "survivorship" note in README.
SYMBOLS = """RELIANCE TCS HDFCBANK INFY ICICIBANK HINDUNILVR ITC SBIN BHARTIARTL KOTAKBANK LT AXISBANK
ASIANPAINT MARUTI SUNPHARMA TITAN ULTRACEMCO BAJFINANCE NESTLEIND WIPRO HCLTECH ONGC NTPC POWERGRID
TATASTEEL JSWSTEEL M&M ADANIENT ADANIPORTS COALINDIA BAJAJFINSV TECHM INDUSINDBK GRASIM HINDALCO
DRREDDY CIPLA EICHERMOT HEROMOTOCO BRITANNIA APOLLOHOSP DIVISLAB BPCL TATACONSUM SBILIFE HDFCLIFE
BAJAJ-AUTO SHREECEM""".split()
SYMBOLS = list(dict.fromkeys(SYMBOLS + """ABB ACC ADANIGREEN ADANIPOWER AMBUJACEM AUROPHARMA BAJAJHLDNG BALKRISIND BANDHANBNK BANKBARODA BANKINDIA BATAINDIA BEL BERGEPAINT BHEL BIOCON BOSCHLTD CANBK CHOLAFIN COLPAL CONCOR CUMMINSIND DABUR DALBHARAT DEEPAKNTR DLF ESCORTS EXIDEIND FEDERALBNK GAIL GLENMARK GODREJCP GODREJPROP HAVELLS HDFCAMC HINDPETRO HINDZINC IDFCFIRSTB IGL INDHOTEL INDIGO IOC IRCTC JINDALSTEL JUBLFOOD LICHSGFIN LUPIN MARICO MFSL MGL MOTHERSON MPHASIS MRF MUTHOOTFIN NAUKRI NMDC OBEROIRLTY OFSS PAGEIND PERSISTENT PETRONET PFC PIDILITIND PIIND PNB POLYCAB RECLTD SAIL SIEMENS SRF SUNTV SYNGENE TATACHEM TATACOMM TATAELXSI TATAPOWER TORNTPHARM TORNTPOWER TRENT TVSMOTOR UBL UNIONBANK UPL VEDL VOLTAS WHIRLPOOL YESBANK ZEEL ZYDUSLIFE ASHOKLEY ASTRAL APLAPOLLO ATUL AUBANK BHARATFORG CROMPTON COFORGE CUB DIXON EMAMILTD GMRINFRA GUJGASLTD HAL IEX INDIANB IPCALAB JKCEMENT JSWENERGY LALPATHLAB LAURUSLABS LTTS MANAPPURAM MAXHEALTH NATIONALUM NAVINFLUOR OIL PHOENIXLTD PRESTIGE RAMCOCEM RBLBANK SCHAEFFLER SUNDARMFIN SUPREMEIND TIMKEN ABCAPITAL ABFRL ALKEM AJANTPHARM APOLLOTYRE ASTRAZEN BALRAMCHIN CAMS CANFINHOME CDSL CESC CHAMBLFERT COROMANDEL CRISIL CGPOWER ELGIEQUIP FORTIS GLAXO GRANULES GRINDWELL GSPL HFCL HONAUT INDIAMART INTELLECT JBCHEPHARM JKTYRE KAJARIACER KANSAINER KEC METROPOLIS NATCOPHARM NHPC NLCINDIA PGHH RADICO RAYMOND SJVN SKFINDIA SONATSOFTW SUNDRMFAST SUZLON THERMAX TRIDENT VGUARD ZENSARTECH AARTIIND AFFLE ALKYLAMINE AMARAJABAT BASF BLUEDART BRIGADE BSE CARBORUNIV CASTROLIND CEATLTD CENTRALBK CHOLAHLDNG CLEAN COCHINSHIP CYIENT DCMSHRIRAM EIDPARRY EIHOTEL ENGINERSIN FINCABLES FINPIPE FLUOROCHEM GICRE GILLETTE GLAND GODFRYPHLP GODREJIND GPPL GRSE HAPPSTMNDS HATSUN HEG HINDCOPPER HUDCO IDBI IFCI IIFL INDIACEM IOB IRB ISEC JKLAKSHMI JMFINANCIAL JSL JUSTDIAL JYOTHYLAB KALPATPOWR KARURVYSYA KIRLOSENG KNRCON KRBL LAXMIMACH LUXIND MAHLIFE MAHSEAMLES MAHABANK MASTEK MEDPLUS MINDACORP NCC NESCO NIACL OLECTRA ORIENTELEC PCBL PNBHOUSING POWERINDIA PRAJIND PRINCEPIPE PSPPROJECT QUESS RAIN RALLIS RATNAMANI RCF RELAXO RITES ROUTE SANOFI SAREGAMA SFL SHARDACID SHOPERSTOP SHYAMMETL SOBHA SOUTHBANK STAR SUDARSCHEM SUNCLAYLTD SUNTECK SUPRAJIT SWANENERGY SYMPHONY TANLA TATAMTRDVR TCIEXP TEAMLEASE TEJASNET TTKPRESTIG UCOBANK UFLEX UNIPARTS VAIBHAVGBL VAKRANGEE VARROC VENKEYS VINATIORGA VIPIND VTL WELSPUNIND WOCKPHARMA""".split()))


def load_nse(folder="data", top=None):
    """Return (close, volume): tables with one column per stock, one row per trading day.
    top=N keeps only the N most traded stocks (average price x volume in rupees over the whole period)."""
    close = pd.read_csv(os.path.join(folder, "nse_close.csv"), index_col=0, parse_dates=True)
    volume = pd.read_csv(os.path.join(folder, "nse_volume.csv"), index_col=0, parse_dates=True)
    if top:
        keep = (close * volume).mean().nlargest(top).index
        close, volume = close[keep], volume[keep]
    return close, volume


if __name__ == "__main__":
    raw = yf.download([s + ".NS" for s in SYMBOLS], start=START, progress=False, auto_adjust=True)
    close, volume = raw["Close"], raw["Volume"]
    close.columns = close.columns.str.replace(".NS", "", regex=False)
    volume.columns = volume.columns.str.replace(".NS", "", regex=False)

    # keep stocks with enough history; fill the odd missing day with the last known value
    enough = close.notna().sum() >= MIN_DAYS
    dropped = list(close.columns[~enough])
    close, volume = close.loc[:, enough].ffill().dropna(), volume.loc[:, enough].fillna(0)
    volume = volume.loc[close.index]
    volume = volume.where(volume > 0, 1)          # zero volume breaks log(); treat as 1

    os.makedirs("data", exist_ok=True)
    close.to_csv("data/nse_close.csv")
    volume.to_csv("data/nse_volume.csv")
    print(f"saved {close.shape[1]} stocks x {close.shape[0]} days  ({close.index[0].date()} to {close.index[-1].date()})")
    if dropped:
        print("dropped (not enough history or no data):", dropped)
